// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8WkLJin707_56oAN-JYXLn9sJw4a6a5I',
    appId: '1:269278317829:web:5a6d8cddfa4b69185dfb6c',
    messagingSenderId: '269278317829',
    projectId: 'todays-language-dev',
    authDomain: 'todays-language-dev.firebaseapp.com',
    storageBucket: 'todays-language-dev.firebasestorage.app',
    measurementId: 'G-N6Y7M30CXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1fDDeRcxr1xV89LOGhgD-wdbkNGxZUQ4',
    appId: '1:269278317829:android:6c51b8ad926dd4c15dfb6c',
    messagingSenderId: '269278317829',
    projectId: 'todays-language-dev',
    storageBucket: 'todays-language-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANWsQdrmcqlCq5KkXaX7lvKD1kxwI_C04',
    appId: '1:269278317829:ios:a496684cc7dc18d35dfb6c',
    messagingSenderId: '269278317829',
    projectId: 'todays-language-dev',
    storageBucket: 'todays-language-dev.firebasestorage.app',
    iosBundleId: 'com.todayslanguage.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANWsQdrmcqlCq5KkXaX7lvKD1kxwI_C04',
    appId: '1:269278317829:ios:a496684cc7dc18d35dfb6c',
    messagingSenderId: '269278317829',
    projectId: 'todays-language-dev',
    storageBucket: 'todays-language-dev.firebasestorage.app',
    iosBundleId: 'com.todayslanguage.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8WkLJin707_56oAN-JYXLn9sJw4a6a5I',
    appId: '1:269278317829:web:ca3c11305eee511d5dfb6c',
    messagingSenderId: '269278317829',
    projectId: 'todays-language-dev',
    authDomain: 'todays-language-dev.firebaseapp.com',
    storageBucket: 'todays-language-dev.firebasestorage.app',
    measurementId: 'G-H6XVT9R1LQ',
  );
}
