"""Regenerate privacy-en.html / terms-en.html from markdown (one-off sync helper)."""

import html as html_lib
import re
from pathlib import Path


def md_to_body(md_path: Path) -> str:
    text = md_path.read_text(encoding="utf-8")
    marker = "**Privacy Policy**" if "privacy" in md_path.name else "**Terms & Conditions**"
    start = text.find(marker)
    if start < 0:
        raise ValueError(f"start marker not found in {md_path}")
    text = text[start:]
    text = re.sub(r"\* \* \*[\s\S]*$", "", text).strip()
    lines = text.splitlines()
    out: list[str] = []
    in_ul = False
    title = "Privacy Policy" if "privacy" in md_path.name else "Terms & Conditions"
    out.append(f"<strong>{title}</strong>")

    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        i += 1
        if not line.strip():
            if in_ul:
                out.append("</ul>")
                in_ul = False
            out.append("<br>")
            continue

        if line.startswith("**") and line.endswith("**") and line.count("**") == 2:
            if in_ul:
                out.append("</ul>")
                in_ul = False
            out.append(f"<strong>{html_lib.escape(line.strip('*'))}</strong>")
            continue

        if line.startswith("| ") and "|" in line[2:]:
            if re.match(r"^\|[-| :]+\|$", line):
                continue
            cells = [c.strip() for c in line.strip("|").split("|")]
            if not in_ul:
                out.append("<ul>")
                in_ul = True
            joined = " — ".join(html_lib.escape(c) for c in cells if c)
            out.append(f"<li>{joined}</li>")
            continue

        if line.startswith("*   "):
            if not in_ul:
                out.append("<ul>")
                in_ul = True
            content = line[4:]
            content = re.sub(
                r"\[(.*?)\]\((.*?)\)",
                r'<a href="\2" target="_blank" rel="noopener noreferrer">\1</a>',
                content,
            )
            content = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", content)
            out.append(f"<li>{content}</li>")
            continue

        if in_ul:
            out.append("</ul>")
            in_ul = False
        content = line
        content = re.sub(
            r"\[(.*?)\]\((.*?)\)",
            r'<a href="\2" target="_blank" rel="noopener noreferrer">\1</a>',
            content,
        )
        content = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", content)
        out.append(f"<p>{content}</p>")

    if in_ul:
        out.append("</ul>")
    return "".join(out)


TEMPLATE = """<!DOCTYPE html>
    <html>
    <head>
      <meta charset='utf-8'>
      <meta name='viewport' content='width=device-width'>
      <title>{title}</title>
      <style> body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding:1em; } } </style>
    </head>
    <body>
    {body}<hr><p><span>This page was generated by </span><a href="https://app-privacy-policy-generator.nisrulz.com/" target="_blank" rel="noopener noreferrer">App Privacy Policy Generator</a> (reviewed and updated for Today's Language).</p>
    </body>
    </html>
"""


def main() -> None:
    base = Path(__file__).parent
    for name, title in [("privacy-en.md", "Privacy Policy"), ("terms-en.md", "Terms & Conditions")]:
        md_path = base / name
        body = md_to_body(md_path)
        html_out = TEMPLATE.replace("{title}", title).replace("{body}", body)
        (base / name.replace(".md", ".html")).write_text(html_out, encoding="utf-8", newline="\n")
        print(f"wrote {name.replace('.md', '.html')}")


if __name__ == "__main__":
    main()
